### ISSUE TITLE
Allowance report 

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/lighthouse-client#1351]
Extract allowance page from Progress summary, and make it as a stand alone report
Add it to JCA portal under Project Control

Report Id: pp-allowance

**Comment by ken-mellem** [comment]
@JoneUE is this already verified?

**Comment by JoneUE** [comment]
@ken-mellem Report is ready, just need to be pushed to prod

**Comment by ken-mellem** [comment]
@MagnusGjosund @Noggling Jone tells me this can be put into PROD now.
See https://github.com/equinor/lighthouse-client/pull/1354

**Comment by MagnusGjosund** [comment]
The report is out in prod. PBI need to publish it in reports admin. @JoneUE follows this up.

Should i close the issue or should we wait for @aman-riaz or @BenSvend to publish it in reports admin?
