### ISSUE TITLE
[Workorder]: WBS table field and filter option

### ISSUE THREAD

**Issue by ken-mellem** [equinor/lighthouse-client#1368]
Column "WorkBreakdownStructure" (WBS) is now available in [Completion].[CompletionWorkOrder_v1].
`ICanHaveWorkBreakdownStructureCode | WorkBreakdownStructure | Work breakdown structure code | string`

This should be replicated - both for Project Portal and JC Portal

- [x] enable the column in the table
- [x] enable filtering on this field

## How to test

- In [JC Portal Test Workorder](https://jc.fusion.test.equinor.com/ConstructionAndCommissioning/work-order/table), you should have the **WBS** column. 
- The WBS is now a field available for filtering

**Comment by ken-mellem** [comment]
Problem is that we do not use that specific endpoint. We use
`Equinor.TI.Fam.Api.Models.Generated.Completion.CustomAPI_WorkOrdersV1` not
`Equinor.TI.Fam.Api.Models.Generated.Completion.CompletionWorkOrderV1`.

**Comment by aman-riaz** [comment]
CustomAPI - views are managed by FAM, so any new changes must go through them. 
I have added a booking in their FAM consumers channel: New colum in CustomAPI_WorkOrders @ken-mellem

**Comment by aman-riaz** [comment]
WorkBreakdownStructure in CustomAPI_WorkOrders_v1 in prod now.

**Comment by ken-mellem** [comment]
Opening for Test

**Comment by AreWiv** [comment]
Verified in test.

**Comment by ken-mellem** [comment]
In PROD.
