### ISSUE TITLE
Workflows steps are not re-rendered in sidesheet when selecting another template in Release control

### ISSUE THREAD

**Issue by Jossilainen** [equinor/lighthouse-client#1380]
When selecting a workflow-template, the steps are rendered as expected in the sidesheet. Then when selecting another template, without closing the sidesheet, the sidesheet is not listing any steps. When closing the sidesheet first steps are listed as expected.

 
![image](https://github.com/equinor/lighthouse-client/assets/76108993/8be77719-1e72-40f5-8327-16562db4a313)

![image](https://github.com/equinor/lighthouse-client/assets/76108993/1196de71-b881-4584-94a7-1c6c80c61362)

**Comment by ken-mellem** [comment]
I would not prioritize this - `won't-fix`.

**Comment by EDUT-Equinor** [comment]
this doesnt seem to be an issue for me? 


![Image](https://github.com/equinor/lighthouse-client/assets/147052136/eb9b957e-cb85-4c6c-8a49-2294ae9eda75)


![Image](https://github.com/equinor/lighthouse-client/assets/147052136/4754f39c-d183-4532-b9b2-346c04467baa)


![Image](https://github.com/equinor/lighthouse-client/assets/147052136/8c2d342b-067d-43f1-a0e8-12fdad8156d9)

**Comment by EDUT-Equinor** [comment]
Closing issue, if it reapears. we reopen issue.
