### ISSUE TITLE
:card_index: Update landing page

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/lighthouse-client#1395]
## Expected outcome

Remove tasks and yammer widgets. Only showing the PBI report. 

## Business Value / Developer Experience

Requested by PO. Remove unnecessary widgets to make the landing page better for experience

## User Acceptance Tests (UAT)

Check if Tasks and Yammer widgets are gone in landing page.

**Comment by espenkalle** [comment]
PowerBI now has full width on the landing page. 
![361622d6-5a95-4ada-8408-0544d685cc4c](https://github.com/equinor/lighthouse-client/assets/108390105/d7bfa3f6-83df-4d5e-923f-7e07f4c1c5b5)


There is still some whitespace on the side but seems to be a PowerBI Issue
![110b1164-421b-40a1-b2c5-8184a8eb9703](https://github.com/equinor/lighthouse-client/assets/108390105/9aeef257-e18a-417d-b96d-d698acbc5587)

**Comment by ken-mellem** [comment]
I miss the picture of the boat... should have had that as a dimmed background image...

**Comment by MagnusGjosund** [comment]
The boat was gone when we started. Someone has stolen it 🤠

**Comment by ken-mellem** [comment]
🚢 ASAP
