### ISSUE TITLE
🐛 Tasks: Homepage - Open task in new tab

### ISSUE THREAD

**Issue by JoneUE** [equinor/lighthouse-client#1415]
https://github.com/equinor/CC/issues/35

When the front page of the portal was changed, the "Notifications" functionality changed.
When you press a task, the sidesheet will be replaced with that linked object (SCR)
You have to click the Notifications then "Tasks" tab when going through actions. adding several clicks to each action. "increased our meeting lenght by 4x".

Tasks should open in a new tab

**Comment by Gustav-Eikaas** [comment]
Just open in new window

**Comment by JoneUE** [comment]
@MagnusGjosund @ken-mellem Får dere satt denne til prioritet?

**Comment by MagnusGjosund** [comment]
Opptatt med noe annet nå. Skal følge det opp de neste dagene.

**Comment by MagnusGjosund** [comment]
This will interfere with the new app loading. @Gustav-Eikaas will look at it

**Comment by MagnusGjosund** [comment]
The fix should be out in test. I need help to test it cause i have none tasks :( I ask the other guys at the office for help tomorrow

**Comment by MagnusGjosund** [comment]
Worked in test. Out in prod soon
