### ISSUE TITLE
Inputs - Links to relevant ISO / P&ID Drawings can be added easily

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1466]
## Expected outcome

 
In the pull out tab, add an area for links to ISO / P&ID drawings where users can manually add the P&ID / ISOs that they need (it would be better if we could just pull all the latest P&ID & ISO Drawings relating to all Tags involved in the RC, and also pull all P&ID / ISO Relating to HTs. I think we can do that, as Atle mentions below:
I think we should pull through P&IDs, ISO, Block and Data Sheets. Need to confirm with Atle the Structure to pull things through.
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/1bb51f61-e309-4ebd-a248-144fb89c6a85)

These are the P&ID / ISOs that we want (example)
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/79d831d9-8e42-4177-87f3-69f5dab6a272)

Here is a picture of how the ISO / P&IDs for LUN (similar to RC) looked in Johan Sverdrup:
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/6c7b84f0-924c-4238-8c8a-4d74e1461d15)

## Acceptance Criteria

 
- [ ] In a Documents tag, there all tags in the RC are listed that are in the Scope tag, and their associated ISOs / P&ID are linked
- [ ] _Stretch_ Block and Data sheet are linked.

**Comment by EDUT-Equinor** [comment]
@atlewee  - Could you confirm how we should connect P&IDs / ISOs to RC requests? Are they automatically picked up from tags, or would ISO / P&ID be manually inputted by a user?

I am unsure how Sverdrup did it, see last pic for LUN view that Sverdrup had.

**Comment by atlewee** [comment]
Info: STID or procosys is best for tag/doc links.
Also If you have the docNumber, you can easily just construct a Stid link from the Number and plant.
(Echo has no documents, echo looks them up in STID API )

**Comment by EDUT-Equinor** [comment]
Great, is the plan that users manually add P&IDs, or is there a way we can pull these in an automated fashion?

**Comment by Gustav-Eikaas** [comment]
Write lookup to stid to get P&ID and ISO's. There is an endpoint for getting this based on the tagNo and the instCode. Should fix the #1542 first. As it will affect the code for handling this

**Comment by EDUT-Equinor** [comment]
Atle answered Kjetil on teams:

**Comment by kjellhaaland** [comment]
@EDUT-Equinor, my current implementation look like this.
Does it look ok?

![Screenshot 2024-01-19 103822](https://github.com/equinor/lighthouse-client/assets/17578087/5bf38001-d1d0-4d1f-8442-a2caa55f643f)

**Comment by EDUT-Equinor** [comment]
closed by mistake - reopening

**Comment by kjellhaaland** [comment]
@EDUT-Equinor, this is now ready for testing.

**Link**: https://jc.fusion.test.equinor.com/ConstructionAndCommissioning/release/table

**Comment by kjellhaaland** [comment]
A new bug appeared in the OPS logs. Could easily be fixed, along with the changes requrested by Ed.

- Failed API calls to STID, should not cause the entire request to fail.
- Document-links should open the document directly.
