### ISSUE TITLE
Handover Transition - bookmarks not saving the colapsed position they were left in

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1478]
## Description

The collapsible bookmarks do not maintain the last position you left them in 

## Reproduce

 
step 1:
open bookmarks: 
![image](https://github.com/equinor/lighthouse-client/assets/147052136/5eecca5c-84c9-492c-9a22-7add581b3318)
Step 2: collapse the bookmarks you dont want to see. 
![image](https://github.com/equinor/lighthouse-client/assets/147052136/02aab203-3726-468c-a1dc-e115cec4be89)
Step 3: CLose the bookmarks tab, with the x 
![image](https://github.com/equinor/lighthouse-client/assets/147052136/feb51eac-334a-4b2b-86cd-8c78c6b6e035)
Step 4: reopen bookmarks tab - notice how the bookmarks have all expanded again and not kept the collapsed position, unlike in the old Fusion Portal.
![image](https://github.com/equinor/lighthouse-client/assets/147052136/edf6fc27-539d-4d0e-9015-09e22740d9ca)

## Expected behavior

When you collapse bookmarks in the Portal, and then reopen the portal, the collapsed settings you last left the page on should be retained.

**Comment by EDUT-Equinor** [comment]
any progress on this?

**Comment by JoneUE** [comment]
Should set default to collapsed, and expand bookmarks for current app

**Comment by JoneUE** [comment]
Not planned to do
