### ISSUE TITLE
Need to extract all related Pipes and Valves to a HT

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/lighthouse-client#1480]
Parent issue: https://github.com/equinor/lighthouse-client/issues/1458

I need to show all related Pipes (not pipetests) and Valves to a HT, but currently i cant fetch this data.

Im not sure about the approach, so i think we need to have a meeting to talk around this. We probably should get help from @JoneUE aswell. I set up a meeting

**Comment by atlewee** [comment]
![image](https://github.com/equinor/lighthouse-client/assets/11732817/40ac6b4a-feb0-4463-bb37-fe8c8afe7fc2)

**Comment by aman-riaz** [comment]
Custom_:HeatTraceCableServiceCompletionTag ready in dev. Will be pushed to prod today. 
Remeber to filter out for Register = "MANUAL_VALVE" and "PIPE_SUPPORT". 
@atlewee  can you confirm is these are the correct type for valves and pipes?

**Comment by EDUT-Equinor** [comment]
CLosed as parent issue is on hold and not planned for JC
