### ISSUE TITLE
Handover Transition - Hanging Garden is not picking up Planned date when there is no Forecast Date

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1481]
## Description

When Forcaste Date is missing on RFOC (maybe RFCC I have not checked), the Planned Date is not being picked up. 

533 CommPacakages missing Dates
![image](https://github.com/equinor/lighthouse-client/assets/147052136/dd96fd54-0f3a-4dc0-b6b7-d57409e9ba7a)

New Hanging Garden:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/cbb8d1fc-f385-4c68-a0c9-dfd0c2dc2ad5)

Old Hanging Garden
![image](https://github.com/equinor/lighthouse-client/assets/147052136/27f6b67a-386e-414d-b31e-8f47eee95d4a)

## Reproduce

Check CommPkg 8637-L01 in New and Old Hanging Gardens as seen above
 
## Expected behavior

if there is a missing RFCC / RFOC Forecast Date, the planned date should be picked up

**Comment by ken-mellem** [comment]
I note that we still have a difference - not in count but presentation. In the new app, the column is put as column 0 - and in the old app, it is the far most future column:

## New
![Image](https://github.com/equinor/lighthouse-client/assets/110427825/5603de41-195f-4f96-83a2-734fb1ad4830)

## Old
![Image](https://github.com/equinor/lighthouse-client/assets/110427825/dd83cd06-2eff-4b90-9960-3357cdf91b72)

@EDUT-Equinor known? This should result in a new Issue if considered unwanted behaviour.  @Gustav-Eikaas

**Comment by ken-mellem** [comment]
@espenkalle fyi

**Comment by EDUT-Equinor** [comment]
good spot, but in the original fusion the N/A are at the front so I think it can stay as it is. :)
