### ISSUE TITLE
Handover Transition - SWCR status code incorrect. e.g.,, Comm. pkg. 8730-H03

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1494]
## Description

Status for SWCR picking up wrong Status.

These two SWCR-status-code for Comm. pkg. 8730-H03. The old version shows "Closed - Rejected" which is correct, and the new version shows "Accepted" which is not the current status. 

## Reproduce

 Old Handover - Correct :
![image](https://github.com/equinor/lighthouse-client/assets/147052136/44c1f3c6-6098-4f5c-b5f8-61c16ae0d361)

New Handover - Incorrect:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/ac13451f-490c-49c1-91a2-b84ab6c96a3c)

**Comment by BenSvend** [comment]
In the data I can see in FAM (their completion view, not one we've created). It does indeed show what is displayed on the bottom image. I don't have access to check how the calculation is made, and I therefore assume that the data is wrong. Should contact FAM for clearification.

![image](https://github.com/equinor/lighthouse-client/assets/133334563/3f0cf4e8-908c-48ea-a387-238a1d194d8a)

**Comment by ken-mellem** [comment]
We recognize the issue - our decision is to remove the SWCR Status field from the view until we get a properly calculated field from source.

**Comment by BenSvend** [comment]
Closing this issue as "Wont fix". Since FAM have indicated that they will remove the Status field from their database until further notice.

Look at the issue below for more information:

- equinor/cc-components#741

**Comment by EDUT-Equinor** [comment]
Hei @BenSvend @ken-mellem - we defo need this issue resolved somehow, have had some more comments today about it not working.

**Comment by EDUT-Equinor** [comment]
Here are some pics i got yesterday on topice - we cant have errors like these if we want users to trust new tools, that is my concern.
Old
![image](https://github.com/equinor/lighthouse-client/assets/147052136/1228fcaa-536c-4c91-ba9f-03e828da2150)


New
![image](https://github.com/equinor/lighthouse-client/assets/147052136/ddda0f5f-eac2-41b5-b636-66caa5273a7b)


Old:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/a48b7b45-2454-4d12-b267-d5bf7a12b8e3)
new:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/3d158f27-a0df-4ad6-9942-ee558de3a101)

![image](https://github.com/equinor/lighthouse-client/assets/147052136/43f1f24d-587b-460e-9d5b-f4fc3a3b02c1)
![image](https://github.com/equinor/lighthouse-client/assets/147052136/06751f96-d0df-4c6a-b569-a5dfc3328034)


Same issue also happening in Query:
Old:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/1ffbd767-36a9-4f9d-8707-865e6a6dc950)
New
![image](https://github.com/equinor/lighthouse-client/assets/147052136/41f9f6ae-ff68-4136-9138-4d588600b8c0)
Please check related Queries in ProCoSys:
 ![image](https://github.com/equinor/lighthouse-client/assets/147052136/66a4b999-b286-47cc-ac7a-73edd777abb4)

**Comment by ken-mellem** [comment]
Closed as duplicate

See
- https://github.com/equinor/cc-components/issues/741

**Comment by ken-mellem** [comment]
@EDUT-Equinor calculation done for Query should be reported in a new separate issue - thanks.

**Comment by EDUT-Equinor** [comment]
yes whoops! i did do that but forgot to remove the query issue here!
