### ISSUE TITLE
Filters - for RC contains (called Step in PHT) .... that is similar to the current step filter

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1496]
## Expected outcome

 ![image](https://github.com/equinor/lighthouse-client/assets/147052136/0c950028-47ba-415e-80e6-2ab04bf89dd4)

## Business Value / Developer Experience

 can then see if your team will be involved in something / if it has been involved in something. e.g., if a step is skipped / redone on an ad-hoc basis

## Acceptance Criteria

 
- [ ] there is a filter as shown in pic.

**Comment by atlewee** [comment]
We have this in both Piping&HT and ScopeChange.
The filter is simply called "Step" in those applications.. 
Maybe it should be named "Contains Step" to be more self explainatory.

**Comment by kjellhaaland** [comment]
@atlewee @EDUT-Equinor I have implemented the filter, and called it "Contains Step".
Is it desirable that the filters in Piping&HT and ScopeChange uses the same naming convention?

Will make a PR when clarified.

**Comment by atlewee** [comment]
Yes that would be prefered If possible :)

**Comment by kjellhaaland** [comment]
It seems like the filter in ScopeChange is similar to the "CurrentStep" filter in RC.

If i understand the request correctly, when the user selects a step in the new "Contains Step" filter, the table should show all RCs where the selected step is either complete or is currently active.

@EDUT-Equinor, is this right?

**Comment by atlewee** [comment]
@kjellhaaland the "Contains step" does not care about step state.
It simply shows RC's that contains the step you selected in the filter. (it does not matter if they are signed/current/not sigend)

**Comment by kjellhaaland** [comment]
@atlewee or @EDUT-Equinor this is now ready for test.

Can you verify that it works as requested?

Link: https://jc.fusion.test.equinor.com/ConstructionAndCommissioning/release/table

**Comment by EDUT-Equinor** [comment]
looks great :) -> go for push!
