### ISSUE TITLE
Functions - History Tab record all changes that are made, not just "Created", "completed" etc.... And include dates that this was done

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1497]
------ Update 05.03 Probably not planned for JC -------

## Expected outcome

 
develop the History tab so it shows useful updates when things change. for example when the MCCR date of something changes. is it possible to add a function that will record these kinds of changes. to help users understand why / what has changed over time.

Essential if any data with an RC ID has changed - the History tab should capture this.   Perhaps easier to do with some things than others. thought I would raise it as thought for discussion
![image](https://github.com/equinor/lighthouse-client/assets/147052136/24fb0e06-e26a-449d-a84b-4ff403067616)

including the sent back information when users sends info back: ATM THis is all that is included.
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/9f628d1d-8a95-4128-a78b-bb8119414937)

## Business Value / Developer Experience

Aid rotation people on what has happened / why the thing they were looking at has now changed.

**Comment by JoneUE** [comment]
You can't get history data from external sources.

**Comment by EDUT-Equinor** [comment]
Useful, but for the next RC, not for JC
