### ISSUE TITLE
Columns - Add columns for Owner and MC status

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1498]
### Will also pick up

- [ ] 🚢 RC: SmokeTest February

UPDATED FOR TEAM-> 17.01.24
Have a column on the sidesheet  for "Owner" which shows the RFO shipped / RFC shipped / RFO accepted / RFC accepted status of the MC package
Have a column on the sidesheet for MC Status of the Tag (if it is OS/OK/PA/PB) with a Link to the Punch list  -> Note -> it is MC status of the TAG not the MC Package

Have a column on the HT table for Signing status of the Tag (Signed Date) - This should take the signing status of the most recently created MCCR assigned to the HT tag
Have a column on the HT table for Signing status of the Tag (Verified Date) - This should take the signing status of the most recently created MCCR assigned to the HT tag
Have a column with included link to the punch (https://procosys.equinor.com/JOHAN_CASTBERG/Completion#PunchList|XXXX) list in PCS for the "STATUS" of the Tag, that shows you OS/PA/PB/OK 
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/0f4fa725-8aa7-4df4-b48a-0cc7d653e056)

EDIT by EDWARD 30.01.2024:
Have a column for Tag Responsible, as if the Tag responsible is SCHF, then the equipment is owned by Equinor, even if it is not RFCC. See below for an example
COlumns left to right
Order for table in Scope
- Tag
- Mounted On
- Links
- "Owner" -> new column
- TAG MC STATUS-> new column
- SIGNING STATUS Signed Date -> new column
- SIGNING STATUS Verified Date -> new column
 - TAG RESPONSIBLE-> new column
- Related HT cables -> but change the name to [HT on Tag/line]
- MC 
- Comm Pack
- Area
- P&ID
- ISO
- WO(open)
- Tag Type

Order for table HT
- Tag number
- links
- Switchboard
- circuit
- "Owner" -> new column
- HT TAG MC STATUS-> new column (OS/PA/PB/OK with underlined blue link to https://procosys.equinor.com/JOHAN_CASTBERG/Completion#PunchList|XXXX
- SIGNING STATUS Signed Date -> new column
- SIGNING STATUS Verified Date -> new column
- Tag(s) heated
- HT Length (m)
- MC
- Comm 
- Area
- P&ID
- ISO
- WO(open)

![Image](https://github.com/equinor/lighthouse-client/assets/147052136/d305a8a3-3a03-4251-9e87-e93e8b3ef917)

**Comment by atlewee** [comment]
1) Not sure if we should use space on a system column. You can see the system from the commPk.. (first two letters)
2) I think it will be better to have a column with "Owner" instead of MC-status.
Status = Handover Status (tag.mcPk) 

| Status | Owner |
| --- | --- |
| OS | Construction |
| RFC approved | Comm |
| RFO approved | Operation |
3) MC status would be nice to show everywhere you see a tag.. visualised with a colored "MC-status dot" just like in the circuit-diagram: 
![image](https://github.com/equinor/lighthouse-client/assets/11732817/97d2245c-09f1-46ef-8fee-a2d9042672b5)

**Comment by Gustav-Eikaas** [comment]
RFC shipped, RFO shipped mc status

**Comment by EDUT-Equinor** [comment]
Handover Status can be found in JC MC app (not Project app)
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/37044435-afd4-4bee-8f29-508190143497)

**Comment by MagnusGjosund** [comment]
Status: the view we are using are missing the datafield that is showing "RFCC Sent", "RFCC Accepted", etc in the picture above. I've asked @BenSvend to add the datafield to the view

**Comment by EDUT-Equinor** [comment]
We need to add something reagrding if the tag has been just signed, or verified -> MC status OK just shows that AKer have Signed the MCCR, but it does not tell us if Equinor have Verified that the work is okay

**Comment by MagnusGjosund** [comment]
The new datafield has been added to Custom_RCTag. Its called CommissioningStatus

**Comment by MagnusGjosund** [comment]
Status: Added "MC Pkg Owner" and "Tag MC" columns to scopetag table. 
PR: https://github.com/equinor/lighthouse-client/pull/1644.

Missing "Signed Date", "Verified Date" and "Tag Responsible" in scopetag table.
Missing "MC Pkg Owner", "Tag MC", "Signed Date", "Verified Date" and "Tag Responsible" in HT table, and reorginizing the columns.

@aman-riaz can you add "signed date", "verified date" and "tag responsible" to custom_RCtagV1? 
and add "MC Pkg Owner"(commissioningStatus), "Tag MC"(mccrStatus), "Signed Date", "Verified Date" and "Tag Responsible" to custom_scope_tagv1=

**Comment by aman-riaz** [comment]
Scope_tag 

- [ ]  signed date
- [ ] verified date 
- [ ] tag responsible
- [ ] tag mc (mccr status) 
- [ ] mc pkg owner (handover status mc based) 
-

**Comment by aman-riaz** [comment]
Custom_Scope_Tag_CC is a newer and more optimized version of Custom_Scope_tag. Idea is to switch over to this view in all apps. This view has additional columns, as follows: 
- SignedDate: **SignedDate** latest signed date of mccr
- VerifiedDate:  **VerifiedDate** latest verified date of mccr 
- Tag MC (MccrStatus): **Status** (worst status) 
- McPkg Owner: **MechanicalCompletionHandoverStatus** ( this is the MC based handover status). 
- As agreed with @EDUT-Equinor i have added **TagDescription** (to find critical Line, see issue [#1467](https://github.com/equinor/lighthouse-client/issues/1467) )
- Also added **FormularType** so you can split the MCCR into its types

I could not find anything called TagResponsible. I suspect you refer to MC Responsible. I can add it today.

**Comment by EDUT-Equinor** [comment]
Thats amazing Aman, thank you so much! I read through, i think that sounds like the data we want :) 

What i mean by TagResponsible is this data field is the column highlighted:
it is who is responsible for that tag
![image](https://github.com/equinor/lighthouse-client/assets/147052136/14f43b90-2e89-4044-891a-61c8179c8c97)

**Comment by MagnusGjosund** [comment]
Cant see MccrStatus, TagDescription and FormularType in Custom_Scope_Tag_CC

![image](https://github.com/equinor/lighthouse-client/assets/54101675/0e7e9d5b-04d3-4ca8-99f8-061b539da3b7)

**Comment by EDUT-Equinor** [comment]
I made a new issue which is relating to this one, to ensure that the columns we create are visible when you are making the RC, not just when you submit the RC - business value explain in the issue below
https://github.com/orgs/equinor/projects/636/views/7?pane=issue&itemId=55664847

**Comment by MagnusGjosund** [comment]
@aman-riaz Looks like i'm also missing TagUrlId in Custom_Scope_Tag_CC

**Comment by MagnusGjosund** [comment]
PR frontend: https://github.com/equinor/lighthouse-client/pull/1730
PR backend: https://github.com/equinor/lighthouse-scope-change-control-api/pull/435

**Comment by MagnusGjosund** [comment]
Everything is ready, except missing one data field on heat trace. We're missing TagUrlId. Without it the link to pcs doesnt work. Was waiting all day yesterday for FAM to push the new datafield to prod, but they never did. Need to talk to Aman before i ask FAM

**Comment by atlewee** [comment]
@MagnusGjosund 
If you already have the "sourceIdentity" (that is the globalId in proCoSys deeplinks)
https://procosys.equinor.com/Redirect/Tag/{globalId}
https://procosys.equinor.com/Redirect/Checklist/{globalId}
no urlId required.... if you have the sourceidentity that is  :)

**Comment by aman-riaz** [comment]
@MagnusGjosund I have added TagUrlId in Custom_Scope_tag_CC. 
Adding PunchUrlId is not so straight forward. Wlill contact you on teams to discuss.
