### ISSUE TITLE
🐛 (RC):  The "Mounted on" column is showing the wrong text.

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1505]
## Description

the "Mounted on" column is showing a string of numbers, when it should be showing the text 50L00081A. 
![image](https://github.com/equinor/lighthouse-client/assets/147052136/1e511f81-2a4e-4398-b47c-45c5a4062cdd)

## Reproduce

go here: https://jc.fusion.equinor.com/ConstructionAndCommissioning/release/table#releaseDetails/d712c53a-8a66-4ab9-625d-08dbf16e3503

Observe the Mounted on column
 
## Expected behavior

mounted on column should show the text in "tag" column. 
![image](https://github.com/equinor/lighthouse-client/assets/147052136/f22727ba-6446-41f5-b220-c813389e8cf1)

**Comment by JoneUE** [comment]
Should be fixed with new update of a view

**Comment by ken-mellem** [comment]
Linked to #1542

**Comment by MagnusGjosund** [comment]
Got fixed indirectly by https://github.com/equinor/lighthouse-client/issues/1542
