### ISSUE TITLE
BUG - Unable to press Submit button in Release Control

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1506]
## Description

I was adding FO tags and HT tags.

I also added HT cables. when these are added, Circuits are also added. 

When trying pressing the Submit button after adding several HTs, I got the messages on the right hand side of the screen

Please note the 82EL011-413 error for example
![image](https://github.com/equinor/lighthouse-client/assets/147052136/1f52b606-1afd-4176-9d39-3a7f7327de36) 

I was able to clear the issue by deleting several HT's and pressing submit, until I was eventually able to submit after deleting all but one Heat Traces

## Expected behavior

We can press the Submit button

**Comment by EDUT-Equinor** [comment]
classic .... I guess we can leave this open and revisit it if / when the bug rears its head again :)

**Comment by ken-mellem** [comment]
if this is not reproducable, then I propose we close it - it can rather be re-opened if it re-occurs.

**Comment by EDUT-Equinor** [comment]
it has now been reopened. discussed with magnus :)

**Comment by EDUT-Equinor** [comment]
@MagnusGjosund - Can we just remove validation on the back end (says Atle) to try and fix this issue :) - mentioned it to him in a meeting

**Comment by EDUT-Equinor** [comment]
Looks good :) - Go for push

**Comment by ken-mellem** [comment]
@MagnusGjosund push to PROD
