### ISSUE TITLE
Functions - Display Work Orders clearly for the tags involved in the RC

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1510]
## Expected outcome

 
We need Commissioning & Operations to be able to understand what WOs are active on the tags that are related to the Release control the user is dealing with. Work Orders will be raised in order to do a Release Control. This will be particularly useful as the platform starts to go hot.

There should be table that picks up WOs that are added to the Tags involved in the "Scope": "Tags involved in this Release Control Process", the table for WO should include: 

- Sequence of work
- WO ID
- WO Title
- The WO progress
- Planned start
- Planned finish 
- Actual Start
- Actual Finish Date
- WO Discipline
- WO Hold
- WO Created Date
- WO Created by

This WO side sheet could look something like the picture below, in a new side sheet tab (The pic below is from the "Work Order" application spliced in)
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/d8a79e13-07e9-431b-be41-e6aec043db6c)

 See below for two images of how Sverdrup displayed WOs for their LUN process:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/e0691fa0-7a3c-4b61-be4e-f50b7bab78ae)
example 2:
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/87f8ca12-80a1-45c9-9393-fc980cec18a4)

ProCoSyS Actual completion date / data on WO completion found here:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/8fab7a8c-f50f-44ce-a74a-acc59395bc18)

Also see sequencing, that is manually added
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/3775e764-75ec-4e1a-9475-236e036e3c9c)

_Stretch_In the main sheet of RC, it should display a column called WO%, this should include a % progress:
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/abedd088-1548-4d79-b352-b027291101fe)

## Acceptance Criteria

 
- [ ] - Separate WO Side-sheet that contains all the WOs
- [ ] WO Sequence - manual inpout
- [ ] - WO ID
- [ ] - WO Title
- [ ] - The WO progress
- [ ] - Planned start
- [ ] - Planned finish 
- [ ] - Actual Start
- [ ] - Actual Finish Date
- [ ] - WO Discipline
- [ ] - WO Hold
- [ ] - WO Created Date
- [ ] - WO Created by
- [ ] _Stretch_ In In the main sheet of RC, it should display a column called WO%

**Comment by EDUT-Equinor** [comment]
Edward needs to re-write this to be WOs that have been raised to do the Release Control

**Comment by EDUT-Equinor** [comment]
potential simple solution as a Stop-Gap measure

1. The "WO(open)" column should display a link to any open WOs that relate to that tag. (Open WO is determined if the WO has an "Actual Completion Date" in ProCoSyS) - We might have to do some logic that says if the WO is at 100% complete OR it has an "Actual Completion date", as sometimes AKER complete work but don't tag the actual completion date (i think) @JoneUE - could you confirm in a comment please?
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/f2c8a372-8bc2-4123-a8cb-ce38c0abcdb3)

**Comment by JoneUE** [comment]
Yeah they do sometimes have 100% progress but no actual completion date. They also have progress on WOs that are in a status where they are not supposed to have any progress

**Comment by EDUT-Equinor** [comment]
The Stop-Gap solution here would be to have Work orders that can be attached as Referances - But that is a bad solution overall:
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/1f2dd02a-38b8-4ca6-8a5e-f6109576ec02)

**Comment by EDUT-Equinor** [comment]
Perhaps there should be a column with checkbox for "Is this an RC Work Order?"  as some WO attached to the tags will not be relating to the RC.

**Comment by EDUT-Equinor** [comment]
maybe we just need this in OPS

**Comment by JoneUE** [comment]
But you can also have multiple WOs for one Tag, so to add a Link is not possible the way things are set up or to add more information about the WOs

**Comment by EDUT-Equinor** [comment]
@JoneUE  - we can just flip the columns around so the WO come first, and Tags come in column 2?
