### ISSUE TITLE
🐛 (RC):  Random commas when tagging flow lines (maybe other tags)

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1511]
## Description

Random commas when  inputting Flow lines
![image](https://github.com/equinor/lighthouse-client/assets/147052136/085811d4-ccb1-4d54-83aa-5178466fde99)

## Reproduce

input some tags with L in them, observe the Related heat trace column and if it has commas. 

## Expected behavior

no commas plz :))))

**Comment by kjellhaaland** [comment]
@EDUT-Equinor, this is now ready for test.
Can you verify that it works as expected?

Link: https://jc.fusion.test.equinor.com/ConstructionAndCommissioning/release

**Comment by kjellhaaland** [comment]
Edward confirmed this was OK via Teams.
Moving to ready for production.
