### ISSUE TITLE
Insulation tag is automatically displayed when searching for a tag

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1512]
Re-written for Idris 220124

When a TAG (e.g., VG20-0650) is added, JC should look for an insulation tag (e.g., VALV-200367-P13) that has a "mounted on" field that reads  VG20-0650.

we will be doing a data dump into PCS from this spreadsheet  that records all the insulation and what it is mounted on Idris: https://statoilsrm.sharepoint.com/:x:/s/JohanCastbergCommissioning/EcDsWNiwWHRIj9Sw4HlDvvoB-HkSHqCNAMHnTBg8n2JE6Q?email=IAMR%40equinor.com&e=dgGQgd

the Insulation tag should then be displayed as a line underneath the TAG automatically.

![Image](https://github.com/equinor/lighthouse-client/assets/147052136/b0420039-4297-4552-a3f5-a1e41912f3ae)

Tag function or Register is what is used to denote insulation tags:
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/70ab81a5-5e03-47eb-94e1-47b0212b7713)

**Comment by EDUT-Equinor** [comment]
This might have to be made as a sidesheet if things are getting too crowded

**Comment by EDUT-Equinor** [comment]
This table going  was going to pick up all the insulation relating to the tags inputted in the table above, right?
then the columns would be:
Insulation tag N.O
Tag n.o that the insulation is mounted on.
Status of the Insulation (OK / OS etc...)
RFC status -> found from RFC shipped, RFO shipped mc status on the mc package
Owner = RFO shipped / RFC shipped
MC status: OK/OS/PB/PA
 
For RFC look at this issue  [Columns - Add columns for Owner and MC status · Lighthouse 📇 Boards (github.com)](https://github.com/orgs/equinor/projects/415/views/51?filterQuery=repo%3A%22equinor%2Flighthouse-client%22+product-area%3A%22cc%2Frelease-control%22++-is%3Aclosed&pane=issue&itemId=45942239)

**Comment by EDUT-Equinor** [comment]
@idrisbo  -> how close is this to completion -> if more than 1/2 days, lets abandon and leave for next version of RC. After discussion with Jone

**Comment by EDUT-Equinor** [comment]
okay perf :) - nice one

**Comment by ken-mellem** [comment]
Stale
