### ISSUE TITLE
Handover Transition - Add filter for CommPackages to enable more effective filtering

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1515]
## Expected outcome

 
Old portal has a filter for CommPacakge. New portal does not

 If someone wants to see just the -M, -l and -T packages, they currently cant do this, they can only search for one "-M" / "-L" / "-T" CommPacakage at a time.
Users may check multiple value at once, e.g., all -m, all -t and all -L CommPackages for example
Old:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/316194cd-50c2-4646-8dca-41c5fa09bbac)

new:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/7b80e432-78f2-438f-b80e-566e72d556ed)

## Acceptance Criteria

 
- [ ] Filter for CommPackages, as in the Old portal

**Comment by atlewee** [comment]
It was removed because of performance. 
The filters was extreammly slow when there is filters with more than 1000 entries/selection boxes
Must make sure it does not make performance useless before adding

**Comment by EDUT-Equinor** [comment]
where are we on this change? Has been requested again this week

**Comment by EDUT-Equinor** [comment]
@atlewee - this would be really useful

we have this feature in MC app:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/851c73a1-1b9f-4d61-b9d1-affd55d3536c)

**Comment by Gustav-Eikaas** [comment]
Making a Comm identifier filter might be the best option here.

**Comment by JoneUE** [comment]
@Gustav-Eikaas Adding the commpkg filter still makes performance issues?
