### ISSUE TITLE
[RC] Clickable links to procosys for Pipe and Valve in circuit diagram. 

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/lighthouse-client#1517]
## Expected outcome

First it's needed to implement Valves & Pipes in the circuit diagram (https://github.com/equinor/lighthouse-client/issues/1458)
Then add clickable links to procosys for Valves & Pipes

Original issue: https://github.com/equinor/lighthouse-client/issues/1464

## Business Value / Developer Experience

Better ux for end user
 
## Acceptance Criteria

Links to the correct site on procosys

**Comment by EDUT-Equinor** [comment]
We can close this. Yes it adds value, but we can do it in future RC versions as JC has other priorities
