### ISSUE TITLE
Management - Members of an RC Group can easily be viewed by hovering over one of the Functional groups

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1522]
## Expected outcome

 
When a user hovers over the RC - MC Scope team, the names of people in that team should display:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/f7cf76b7-419f-4ac9-84b2-75a2f491ad3b)

The people to include in this list exist here in PROCSOYSS:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/5bdf1011-44fb-4afb-9853-603ea11dde06)

here is How Johan Sverdrup displayed this information when hovering over a team in the workflow:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/0d7f9368-32d1-4208-8113-b7183b89931a)

## Acceptance Criteria

 
- [ ] Can hover over RC - XXXX and show all those in the RC - XXX functional group

**Comment by atlewee** [comment]
I guess this is already available on the backend.. maybe not the persons..
But they are served together with the functionalRoles in ProCoSys API:
( this is also where the common email is stored )
![image](https://github.com/equinor/lighthouse-client/assets/11732817/9ef80166-9665-4b93-93c9-06114bea37f9)
![image](https://github.com/equinor/lighthouse-client/assets/11732817/4631eb74-aeb5-47e0-9898-ce4c967281b6)

I guess it is also available in FAM in the Library table.. ProCoSys search:
![image](https://github.com/equinor/lighthouse-client/assets/11732817/2f8327b9-24bb-4558-b9b2-5a578928bfa9)

**Comment by EDUT-Equinor** [comment]
https://github.com/orgs/equinor/projects/636/views/7?pane=issue&itemId=53823399
