### ISSUE TITLE
Major RC Upgrade- Adding test results to the WorkFlow

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1523]
## Expected outcome

 
Example of how this could look/work:

1. here you can see the three heat traces in this RC
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/57e947c8-c4be-4016-bbbe-a6e1cfc96cbf)

2. The three HT that the user added to the flow would then appear under the HT tags tagged in the form, these would appear in a list
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/9b9fb62c-21f8-4457-a6e3-1c7dc6e481d9)

menu 3. After inputting test results, the user would then sign this out with a comment: 
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/93badca8-762c-4c2b-9eff-e961e8e42a88)

Menu 4. The end result would look like this in the workflow:
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/bc4b7eff-a426-4263-a100-df1aaf454230)

The test results would be the same as the MCCR being conducted, in this case the A Test has the below options in ProCoSyS:
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/7d90b9de-bb5e-4aab-a547-06d2fcac24f3)

## Acceptance Criteria

 
- [ ] Menu to add test results
- [ ] Picks up HTs from Scope menu, even if HT are added later than when the Scope was initially made.

**Comment by atlewee** [comment]
Info: The workflow is made ready to support criterias.
We can add a criteria to upload an attachment for f.eks. A/B-test steps ++
Frontend and endpoints for this is not implemented yet, so not a small task.

( Even better would be to assign procosys checklists that has to be filled out directly in the flow )

**Comment by EDUT-Equinor** [comment]
@atlewee Is "assign procosys checklists that has to be filled out directly in the flow" still the best way to do this after our discussion today. Believe we are now planning to make checklists be in Release Control, and not procosys.

**Comment by EDUT-Equinor** [comment]
this should actually be inline with the results... edward will update the ticket.

**Comment by EDUT-Equinor** [comment]
Covered in https://github.com/orgs/equinor/projects/636/views/7?pane=issue&itemId=54883408
