### ISSUE TITLE
🎁: Management - Release Controls should be send as documents to ProCoSyS similar to SCRs

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1525]
--- Edward 18.03 Can this be the same as the code in SCRs? then there is not much Dev time? ---

ATLE 18.03 ---- "Maybe we just need to send RCs from backend and add the RC document type in PCS" ---
in PCS we currently have SCC Scope Change Request as a Document register, if we add an "RC Release Control", and we have the following data sent to PCS:

- Comm.Packs
- RC-ID
-  Title, starting with Status (if its Open or Closed or Voided) - [the same as SCRs are done]

![Image](https://github.com/equinor/lighthouse-client/assets/147052136/55c59d86-27f2-44c2-9fae-fb223fde98bf)

EDIT: Gustav
This requires setting up TIE to send RC's. Should be easy on our side but it requires PCS to set up a TIE interface for receiving RC's and mapping them appropriately.

![Image](https://github.com/equinor/lighthouse-client/assets/147052136/e4ee29ce-e225-47a4-9579-f0bf11530a2a)

**Comment by EDUT-Equinor** [comment]
We will now Create RC docs instead of creating punches - so this is a greater priortiy. Edward will make a good pictures soon.

**Comment by Gustav-Eikaas** [comment]
This needs prioritization. Its not necessarily a big issue but it requires some input from resouces in PCS. We dont want to bug them if we dont have the capacity to see it through

**Comment by Gustav-Eikaas** [comment]
Some bumps in the road

The RC classification was created in PCS library. Seemingly identical to the SCC one
![Image](https://github.com/equinor/lighthouse-client/assets/89254170/a2af42fa-dd65-4eff-be25-e1af3875bc02)

When running locally and sending a simple RC via TIE to PCS. I tried to make it as similiar as possible to the one for SCC. The error message is incomprehensible
![Image](https://github.com/equinor/lighthouse-client/assets/89254170/8e889da2-039e-4ad1-86de-426aacdf2ebe)
