### ISSUE TITLE
🐛 (RC):  All steps should allow "Add contributor", and anybody should be able to add contributors to workflows and insert comments

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1530]
## Expected outcome

The option "Add Contributor" seems to only be available at some steps in the RC process, and We should be be able be add Contributors / text no matter what step in the process we are at. 

Any functional roles tagged in the workflow should be able to add Contributors / text   
![image](https://github.com/equinor/lighthouse-client/assets/147052136/026bde1b-d89b-4746-a569-5a37b3b60e8f)

## Business Value / Developer Experience

 
So we can better describe what is to be done during a step

## Acceptance Criteria

 
- [ ] Add Contributor is available on any step in the process
- [ ] Add Contributor is available to all functional groups tagged in the RC

**Comment by Gustav-Eikaas** [comment]
Adjust the policy to allow add contributor on any step. Also applies for SCC. 

Can not add contributors on signed steps
Can only add contributors to a step if you're the person assigned.
