### ISSUE TITLE
BUG - Inconsistency between Admin Area and Workspace. New workflows / steps do not appear in workspace.

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1531]
Error
## Description

The Admin area and workspace seem to not be syncing 

Workflow options in the workspace are as shown in this list (plus more options when you scroll down):
![image](https://github.com/equinor/lighthouse-client/assets/147052136/3f26a9cb-147c-4999-9c8b-0659d8b802c6)

However, in the admin area, it only shows two steps? I just added "Recertify Equipment" as a step- this is not appearing in the workspace.
 ![image](https://github.com/equinor/lighthouse-client/assets/147052136/0b8289ed-c859-42e8-aef3-7c20fdc0db77)

Additionally, 
the workflows in the admin area look like this:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/58994082-06c6-4d84-bf5c-61a54707df51)
but look like this in the workspace:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/83338358-2b52-408d-a580-56ca80bf45ae)

## Reproduce

Observe the differences between Admin area and the workspace 

## Expected behavior

All the steps we have added should be shows in the Admin area

**Comment by MagnusGjosund** [comment]
PR: https://github.com/equinor/lighthouse-client/pull/1535
