### ISSUE TITLE
Handover Transition - Query tab not displaying all queries

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1540]
Error
## Description

Query is not picking up all queries, see below that two queries  in Handover Old, but just one in Handover new. 
Also, the status should be closed, accepted. Not just "Closed"

Handover Old:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/a7c87bc3-4e13-45d5-8c32-526deb46bccc)

Handover New:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/7c2f132c-7621-4b27-8744-718b32ed6961)

Please check related Queries in ProCoSys:
 ![image](https://github.com/equinor/lighthouse-client/assets/147052136/8ddb2abb-550f-4714-88e0-9fad4e1d5bf8)

## Reproduce

see diff between 7000-H16 new and old, and observe in ProCoSyS

**Comment by Gustav-Eikaas** [comment]
![image](https://github.com/equinor/lighthouse-client/assets/89254170/4f418294-b4ce-45e4-8b44-953ba449a712)
From FAM. one of the CQ's have wrong project

**Comment by EDUT-Equinor** [comment]
@Gustav-Eikaas - Can this be fixed easily / can we push it to be fixed?

**Comment by Gustav-Eikaas** [comment]
tbh I have no idea who to contact about fixing this. Seems like a business decision? @JoneUE @atlewee ?

**Comment by JoneUE** [comment]
It should be fixed with PCS sending a new dumb of data to FAM

**Comment by atlewee** [comment]
I do not think it will be fixed with a new dump to FAM, as this Query has Project "JOHAN_CASTBERG" and the portal filters on projectNumber.

It can be fixed by removing project filter on Query tab in SQL.  ( It is already filtered on a CommPk project? )
This way it will have same logic as in ProCoSys
( ProCoSys-CommPk can have Queries from multiple projects )

**Comment by JoneUE** [comment]
In ProCoSys it's on the right project code. So could have been an error when it was first sent. There is a closed project for Johan Castberg with this project code

**Comment by MagnusGjosund** [comment]
Is this still an issue?

**Comment by ken-mellem** [comment]
Data issue. Closed.
