### ISSUE TITLE
Add MC packages as a filter and move the System filter and the MC Package filter to the left hand side of the filters

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1541]
## Expected outcome

 
Add MC packages as a filter and move the System filter and the MC Package filter to the left hand side of the filters - discussed with Aman on Teams
![image](https://github.com/equinor/lighthouse-client/assets/147052136/82e2dcc6-4819-4bdd-aee5-f65fde378a6e)

**Comment by aman-riaz** [comment]
- [ ] Add MechanicalCompletionPackage as a column in the table 

![Image](https://github.com/equinor/lighthouse-client/assets/112379863/3310c19f-5edd-4c1e-a0ae-f60e0383630c)

- [ ] Add MechanicalCompletionpackage as a filter (hidden filter)
