### ISSUE TITLE
🐛 (RC): Cant find insulation box tags

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1542]
## Description

 
I cant find this tag in ProCoSyS: I expect to be able to find it.
[VALV- 21L60447A-P19](https://procosys.equinor.com/JOHAN_CASTBERG/Completion#Tag|118796943)

We need to enable searching for dummy tags. Atle says it is in the  [Completion Register] from FAM. 

The tags should be searchable in the field "Tag involved in this release control"
![image](https://github.com/equinor/lighthouse-client/assets/147052136/9cfe2f8a-9a4d-48fb-a629-955bb987d6b3)

**Comment by JoneUE** [comment]
![Image](https://github.com/equinor/lighthouse-client/assets/73601851/1d8d6602-2d80-4037-91c7-9c73436ecb5a)

**Comment by JoneUE** [comment]
Nå kan viewet Custom_RCtag brukes til både søk og legge til tag for release control. Men viewet må også utvides til å få med mountedOnTag som nå mangler i CompletionRegiser og CompletionRegisterView. Etter at dette er lagt til kan det også lages en kobling til Related HT Cables

**Comment by MagnusGjosund** [comment]
Gir du beskjed når du får beskjed at det ikke lenger mangler?

**Comment by MagnusGjosund** [comment]
Update before christmas: Benjamin made a new view, Custom_RCtag. This view made the dummy tags avaiable through search, but when storing the data in our database, the database expect more data than the view serves. This will entail a big technical debt. 
TODO: Add the remaning data to the Cusom_RCtag view. See screenshot below

![image](https://github.com/equinor/lighthouse-client/assets/54101675/3fb7b237-73e5-49ea-8b61-639471aa39f4)

**Comment by JoneUE** [comment]
@MagnusGjosund Are you able to remove some of these columns? not all of them are necessary

**Comment by Gustav-Eikaas** [comment]
To solve this:
Reduce the sql table to just one table containing tagId, and tag type then resolve on the fly and feed from fam to frontend

**Comment by MagnusGjosund** [comment]
PR Frontend: https://github.com/equinor/lighthouse-client/pull/1611
PR Backend: https://github.com/equinor/lighthouse-scope-change-control-api/pull/376 and https://github.com/equinor/lighthouse-scope-change-control-api/pull/401
