### ISSUE TITLE
Add default text to issues description

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1546]
## Expected outcome

 
Discussed to have a default text as shown below instead of some custom inputs to speed up development.

![image](https://github.com/equinor/lighthouse-client/assets/147052136/c115ac6b-6e60-42cd-a629-d6b6bcf914f8)

## Acceptance Criteria

 
- [ ] see pic - the fields in that pic
- [ ] would be good if this text was also in bold

**Comment by MagnusGjosund** [comment]
Approved in test. Its out in prod now
