### ISSUE TITLE
🐛 (RC): Area only appears after pressing submit. 

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1554]
Error
## Description

 
Areas not present when creating the Scope:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/9aaa0963-8f29-4f86-b974-b26df1b886d6)

Areas only appear after clicking submit:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/77ad6b58-6e3d-4890-953d-78cd1c84944b)

## Reproduce

add some tags / HT and observe after pressing submit
 
## Expected behavior

areas appear when creating the areas

**Comment by kjellhaaland** [comment]
@EDUT-Equinor this is now ready for testing in the test environment.

Can you verify that it works as requested? :)

Link: https://jc.fusion.test.equinor.com/ConstructionAndCommissioning/release/table

**Comment by EDUT-Equinor** [comment]
Great -> go for push!!

 this is a really nice quality of life improvement for the coordinators, in every meeting i have had to create a release control we can never find the area that something is in.... so I have to remember to create the RC -> then see area of tag -> and then edit the RC again.... its easy for me to forget this and it leaves less chance that the system responsible gives me the wrong area :)
