### ISSUE TITLE
Workflow - Allow users to send back a workflow if they accidently sign something out

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1556]
## Expected outcome

 
someone can sign something out by accident, but cant send the workflow back to them. e.g., circuit isolation. Hence RC - Coordinator should always be after

## Acceptance Criteria

 
- [ ] when selecting 
- [ ] items which covers
- [ ] the expected outcome

**Comment by Gustav-Eikaas** [comment]
Reintroduce unsign concept. Ignore email problems for now
