### ISSUE TITLE
Circuit Diagram - Remove the "Edit Isolations button 

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1557]
UPDATE 05.03 
---- After discussions with Ops - they will not use the Circuit Diagram as it will take a lot of dev time, better to spent dev time on other things ------

Please can we REMOVE the "Edit Isolations" button in the circuit diagram 

![Image](https://github.com/equinor/lighthouse-client/assets/147052136/ccf9e6d5-d1ec-46fb-a199-c244825502b8)

**Comment by Gustav-Eikaas** [comment]
Will add permission check to this endpoint validating the functional role.

**Comment by EDUT-Equinor** [comment]
looks good in test :)

**Comment by EDUT-Equinor** [comment]
go for push
