### ISSUE TITLE
Workflow - Only RC Coordinator can "Void" an RC

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1560]
![image](https://github.com/equinor/lighthouse-client/assets/147052136/4b4d7c8a-becf-46df-beee-09752b5d1a85)

**Comment by Gustav-Eikaas** [comment]
Can hopefully be fixed in PCS by adjusting privileges

**Comment by EDUT-Equinor** [comment]
fixed :)
