### ISSUE TITLE
Attachments - Can we do something smart so they can be viewed in App?

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1570]
I.E dont need to be downloaded and can have text captions?

open to all ideas on this one

**Comment by Gustav-Eikaas** [comment]
There are a lot of libs for previewing pdf files without downloading them https://projects.wojtekmaj.pl/react-pdf/

**Comment by Gustav-Eikaas** [comment]
Seeing as how browsers have excellent support for viewing both pdf and txt files I think we can change the behavior to open the attachment in a new browser tab. This will probably feel way more smooth to the user

**Comment by Gustav-Eikaas** [comment]
![image](https://github.com/equinor/lighthouse-client/assets/89254170/336276a4-d622-4183-ad40-f09a9f7b56a7)
Looks like this when you open a pdf in native edge

**Comment by Gustav-Eikaas** [comment]
This is a better solution than the current one IMO in any case. 

Dev context:
The attachments are all tagged as octet-stream so we need to set the correct file headers

**Comment by EDUT-Equinor** [comment]
Lets do this in the next version
