### ISSUE TITLE
Workflow - Make it so you can only SIGN once all contribution steps completed

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1571]

**Comment by Gustav-Eikaas** [comment]
You will get a warning in the form of a modal if you try to sign with pending contributions. We deliberately designed it this way to prevent a flow from stopping if a contributor is unavailable.

**Comment by EDUT-Equinor** [comment]
we had a discussion last week with Atle, who said we should go ahead with this change, as it is confusing for users that dont know the tool, what the diff between contributer / signer is. 

This will be a good test for the final solution, (where we have automatic requirements for next steps such as buttons that automatically sign out a circuit as isolated when you click it and sign
