### ISSUE TITLE
🐛 : Workflow deletes contributors when you edit workflow in any way

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1576]
Workflow seems to regenerate each time you press submit.

we want contributors to not be deleted after editing workflow 

step 1. see contributors added
![image](https://github.com/equinor/lighthouse-client/assets/147052136/ae19bc2b-a8a0-4dca-90e5-767150085a39)

step 2. go to edit function and then press save
![image](https://github.com/equinor/lighthouse-client/assets/147052136/75d5dbb4-aabc-490d-91df-5a12c3eff374)

step 3. observe workflow again:
![image](https://github.com/equinor/lighthouse-client/assets/147052136/19e2e01e-34e7-42b1-9943-0e86c991f61c)

**Comment by Gustav-Eikaas** [comment]
dev context:
When editing the flow the context of which steps exists are lost. The new steps in the flow is "replaced" with new steps

**Comment by Gustav-Eikaas** [comment]
Not fixed but with the markdown change #1737. This wont be necessary to fix. I removed the ability to add contributors ahead of the current step.
