### ISSUE TITLE
MC in JC 

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/lighthouse-client#1587]
Onboarding the new scaled MC into JC

**Comment by JoneUE** [comment]
@Gustav-Eikaas this can be closed?

**Comment by Gustav-Eikaas** [comment]
I kept it open for feedback and things worth noting but I have not heard anything. No news is good news

**Comment by ken-mellem** [comment]
Looks good
![image](https://github.com/equinor/lighthouse-client/assets/110427825/a4025fd9-db0a-4c56-8b11-cb1298dff85b)
