### ISSUE TITLE
status shows as completed when it should be in progress 

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1593]
![image](https://github.com/equinor/lighthouse-client/assets/147052136/e4a53939-361c-49f6-b517-1b4e3ee4fa06)

**Comment by Gustav-Eikaas** [comment]
This field is using the workflowstatus so we can either fix the workflow statuses (supposed to be part of the admin tool) or we can calculate the status in some other way

**Comment by EDUT-Equinor** [comment]
closed as we deleted this column
