### ISSUE TITLE
Functional role should stay when signing out in RC

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1595]
When you sign out in RC, we do not want the functional role to disappear. it should say "Stian Methis" signed out on behalf of "RC - SYS 43 Flare system"

![image](https://github.com/equinor/lighthouse-client/assets/147052136/847d4d34-adc8-46f1-851c-ce5767a240c2)

**Comment by Gustav-Eikaas** [comment]
Could we do Stian Mehus(RC-comm)? @EDUT-Equinor

**Comment by EDUT-Equinor** [comment]
yes -> it would be stians RC FR tho, not RC-Comm
