### ISSUE TITLE
Have a drop down arrow for contribution steps that shows all contributions when you click the down arrow. 

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1600]
When signing out contribution steps, after pressing the sign button -> all contributions disappear at the moment, they should be under a drop down arrow and still be able to be found
![image](https://github.com/equinor/lighthouse-client/assets/147052136/dff369a2-7496-4b60-97cc-4c1f2c4e0afa)
see pic below of contributions disappearing
![image](https://github.com/equinor/lighthouse-client/assets/147052136/ab013c80-03e7-45bd-9b1b-322638aca6c9)

Down arrow like this for each bit of workflow that has contributions, there is the option to expand the contributors, and the current step always has its contributions expanded
![image](https://github.com/equinor/lighthouse-client/assets/147052136/7d0d0ad4-150e-4e9e-aa0d-70000e877039)

**Comment by Gustav-Eikaas** [comment]
@EDUT-Equinor Can you have a look at how this is solved in Scope Change Control and see if a unified solution could be satisfactory?

**Comment by Gustav-Eikaas** [comment]
It's an easy fix making it look like this
![image](https://github.com/equinor/lighthouse-client/assets/89254170/6df66b88-09bd-4a25-8a0f-11e36a2498fe)

**Comment by EDUT-Equinor** [comment]
looks great :) go for push
