### ISSUE TITLE
Workflow: add a way to reject contributions / let someone know there is an error

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1602]
some way to reject a contribution as needing rework.

e.g., a "REJECT CONTRIBUTION WITH COMMENT" button

![Image](https://github.com/equinor/lighthouse-client/assets/147052136/ea849c99-7f14-45c9-8449-cbf87e4e67a8)

RC  -Coordinator can just add another step after rejection is done / we have a button called "UNREJECT WITH COMMENT"

**Comment by Gustav-Eikaas** [comment]
Currently looking into what is needed to dynamically add Criterias instead

**Comment by Gustav-Eikaas** [comment]
## Screenshot
Estimation is 1 step with 2 criterias.
Contributors are added on the step level so they are currently just rendered at the bottom of the step
![Image](https://github.com/equinor/lighthouse-client/assets/89254170/a67cf77a-6aaa-4c03-88ef-b6e27e130388)



## Frontend
Visually this change requires some frontend work to both css and button visibility

## Backend
Still looking into all the event stuff with notifications/tasks etc.
May need to adjust some workflow logic

## Logic
Unsigning when one of the criterias in the current step is signed will work but clear the signing in the current step.

If both signs the workflow proceeds.
If both rejects the workflow is sent back to previous step.
If one rejects and one signs one of the persons have to update their response to either reject og sign.
When contributors are added all criterias are unavailable for signing until all contributors have contributed.

**Comment by Gustav-Eikaas** [comment]
The original description of the issue was `RC -Coordinator can just add another step after rejection is done / we have a button called "UNREJECT WITH COMMENT"`
So I think doing this with criterias would be adding a criteria with `add another step after this one to fix xyz` and assigning RC - Coordinator. Alternatively just use the criteria directly for performing the missing work

**Comment by EDUT-Equinor** [comment]
@Gustav-Eikaas -> can we combine this issue into this one? https://github.com/orgs/equinor/projects/636/views/7?pane=issue&itemId=54883408

**Comment by Gustav-Eikaas** [comment]
With the implementation of the new Markdown change #1737. This is no longer required
