### ISSUE TITLE
JCA Job analytics

### ISSUE THREAD

**Issue by JoneUE** [equinor/lighthouse-client#1603]
I've made a new report for JCA management that both Aker and Equinor will be using and grooming together. 

Could you create a new App in the portal for a PBI report. 

Current name is Jobs analytics

I will add link to the PBI report here https://statoilsrm.sharepoint.com/sites/FusioniPRD/Dashboards%20and%20MPP/Forms/AllItems.aspx?OR=Teams%2DHL&CT=1687341305262&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA1MDEwMDQyMiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&id=%2Fsites%2FFusioniPRD%2FDashboards%20and%20MPP%2FReports%20Into%20Fusion%20%28RIF%29%2FCCH%2FJohan%20Castberg%20Portal%2FProduction%2FPP%20Jobs&viewid=f853cde1%2D6ede%2D47a2%2Da60a%2D7a9b1e81dc92

**Comment by JoneUE** [comment]
@MagnusGjosund eller @idrisbo  Hei, får du laget en PBI app i portalen så kan @aman-riaz lage en rapport i reports admin i Fusion og gi dere en Id som kan brukes. Dette har veldig høy prioritet hos Castberg nå. Hvor vi har fått Aker til å også bruke dette

**Comment by aman-riaz** [comment]
Report added in Fusion Reports admin with global id: pp-jobs-analytics 
Sign-off planned 30.01.24

@JoneUE Can you please fill in the [development document](https://statoilsrm.sharepoint.com/:w:/r/sites/FusioniPRD/Dashboards%20and%20MPP/Reports%20Into%20Fusion%20(RIF)/CCH/Johan%20Castberg%20Portal/Production/PP%20Jobs/PP%20Jobs%20-%20PBI%20Development%20Document.docx?d=w51047b14b67f40299437cbef08676472&csf=1&web=1&e=yKdrZd) before the meeting tomorrow.

**Comment by ken-mellem** [comment]
Acknowledged

**Comment by aman-riaz** [comment]
Report now out in prod: https://jc.fusion.equinor.com/ConstructionAndCommissioning/jca-job-analytics?tab=powerbi
