### ISSUE TITLE
🐛  RC when renaming a worklow page crashes

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/lighthouse-client#1605]
After renaming a workflow the page becomes unusable. Check the other actions in admin tab probably more bugs lurking.
![image](https://github.com/equinor/lighthouse-client/assets/89254170/9084ba8c-4463-4be0-bb2e-1f280d5593d9)

**Comment by EDUT-Equinor** [comment]
not too major issue, we can live with it. closing issue
