### ISSUE TITLE
Jobs analytics: added drillthrough for commpkg

### ISSUE THREAD

**Issue by JoneUE** [equinor/lighthouse-client#1626]
Added filter for Form Responsible and Clearing by in countdown page, and drillthrough from countdown page to see punches, MCCRs, Mcpkgs and SCRs

New version added
https://statoilsrm.sharepoint.com/sites/FusioniPRD/Dashboards%20and%20MPP/Forms/AllItems.aspx?OR=Teams%2DHL&CT=1687341305262&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA1MDEwMDQyMiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&id=%2Fsites%2FFusioniPRD%2FDashboards%20and%20MPP%2FReports%20Into%20Fusion%20%28RIF%29%2FCCH%2FJohan%20Castberg%20Portal%2FProduction%2FPP%20Jobs&viewid=f853cde1%2D6ede%2D47a2%2Da60a%2D7a9b1e81dc92

**Comment by aman-riaz** [comment]
Report out in prod: https://jc.fusion.equinor.com/ConstructionAndCommissioning/jca-job-analytics?tab=powerbi
