### ISSUE TITLE
🐛 void RC voids random RCs 

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1631]
![image](https://github.com/equinor/lighthouse-client/assets/147052136/7d7a111e-0072-487f-9a87-a371e755260e)

**Comment by MagnusGjosund** [comment]
Reproduce: Open a RC, then open another one or multiple. When you void, you're voiding the first RC you opened. 
Eg you open RC1, then open RC2 and you try to void RC2, then you will void RC1 since that's the first RC you opened

**Comment by MagnusGjosund** [comment]
PR: https://github.com/equinor/lighthouse-client/pull/1700
