### ISSUE TITLE
bug: random lines appear when creating RC

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1632]
![image](https://github.com/equinor/lighthouse-client/assets/147052136/d39b6e62-38b4-4404-a326-0ed427976f3f)

**Comment by Gustav-Eikaas** [comment]
@MagnusGjosund You can now fix this bug

**Comment by MagnusGjosund** [comment]
PR: https://github.com/equinor/lighthouse-client/pull/1682
