### ISSUE TITLE
🐛 : Void button requires text before you submit like in SCR

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1638]
---- ONLY DO THIS IF ITS A SMALL PICEC OF WORK LESS THAN 1/2 day. This comment feature is already in SCR, can we steal the code from there? --- 

the void button in RC does not make you input text when voiding. 
So atm the one click Void button and Edit are next to each other haha -> maybe we can do a quick fix on that 

![0aa06d98-5330-4d9d-a1d4-cc9c7f71282b](https://github.com/equinor/lighthouse-client/assets/147052136/6a766143-cc1d-4190-9fef-c0de64fb6bca)

**Comment by MagnusGjosund** [comment]
Is there an actual need for having a reason for voiding? Could we remove "Reason for voiding" in the email instead?

**Comment by EDUT-Equinor** [comment]
the reason to have this is to make it harder to accidently void something, i.e., when you void something, you have to provide a comment first as a check. Else RC can be voided with easy misclick, we dont want that to happen when in ops, as someone might think a circuit is isolalated / not isolated when it is not. the edit and void buttons are right next to each other. 

i accidently voided an RC once, and when you void the RC, it stays open in the sidesheet, so not immediately clear it was voided
