### ISSUE TITLE
BUG: three RC created when I just created 1 RC

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1650]
![image](https://github.com/equinor/lighthouse-client/assets/147052136/64937e1a-4e80-410e-8120-1b9efd0e06fd)

three RC created when I made just 1, I guess its a bug. I make an issue about it here:

**Comment by Gustav-Eikaas** [comment]
I think this should be fixed now, lets keep it open for a few more days to ensure its actually fixed
