### ISSUE TITLE
🐛 : Missing System / Comm Pack / circuit / Area columns and filters in RC tool

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1652]
---- ATLE 22.03 is it possible to make a local cache that looks up what circuits are connected to HTs? Then we use the local cache to make a column and filter that updates every 15 mins (the reason to update is to catch the new RCs that are created). Maybe you could make some logic that updates the cache when a new RC is made? ---

We need the following filters included in Metadata and have columns:
System
Comm Pack
Circuit
Area

![image](https://github.com/equinor/lighthouse-client/assets/147052136/d1344f73-108b-46d5-afbe-8692fd43b575)

**Comment by MagnusGjosund** [comment]
Seems like this is the fields that are missing when loading the table and filters

Area
Attachements
Circuits
CommPkIds
CommPkNos
CreatedBy
ModifiedBy
Switchboards
Systems

**Comment by MagnusGjosund** [comment]
We have a duplicate https://github.com/equinor/lighthouse-client/issues/1675. I will close the duplicate issue

**Comment by EDUT-Equinor** [comment]
these columns are now temp removed as data was NULL. we need them back for April.

**Comment by MagnusGjosund** [comment]
Agreed to implement System, Comm Pack, Circuit, Area, CreatedBy and ModifiedBy. These is the only fields that is needed

**Comment by Gustav-Eikaas** [comment]
CommPkg and system is added.

Performance implications
- [ ] CreatedBy
- [ ] ModifiedBy

Hard to implement without data becoming stale
- [ ] Circuit
- [ ] Area

**Comment by aman-riaz** [comment]
@MagnusGjosund  are there any fields in this issue that needs to be added to any view?

**Comment by MagnusGjosund** [comment]
No need to add any fields

**Comment by JoneUE** [comment]
Remaining filters has been added or can be added to the analytics
