### ISSUE TITLE
HT disappear and sometimes reapear

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1665]
WHen you add HT. HT will sometimes all disappear from Scope tab. Then they have sometimes reappeared after a period of time. When they reappear they appear to duplicate themselves.

rc examples of issue. 162 this morning
176 this afternoon
177 just duplication issue this afternoon

172 dispeared at 1416

**Comment by Gustav-Eikaas** [comment]
Not really **fixed** but mitigated by returning all tags with null fields if fam doesnt respond as expected

**Comment by ken-mellem** [comment]
Reported in FAM Consumer

![Image](https://github.com/equinor/lighthouse-client/assets/110427825/4a07a423-40ee-4324-8e68-4c2d4dfe3104)
