### ISSUE TITLE
Creating workflowstep gives 405.

### ISSUE THREAD

**Issue by idrisbo** [equinor/lighthouse-client#1669]
When creating a workflow step, the server returns 405 for /workflow-available-steps.

**Comment by kjellhaaland** [comment]
![image](https://github.com/equinor/lighthouse-client/assets/17578087/bfd67985-6d0b-42b0-8ac5-12901a180e66)

**Comment by EDUT-Equinor** [comment]
is this still an issue? Closing issue as  we have not experienced it
