### ISSUE TITLE
Inputs - Due date should be changed to "Target Date"

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1688]
ops need to know how long a HT can be left disconected for - they say if you need to manage a HT being isolated for a certain time and its limited, you keep close control

![Image](https://github.com/equinor/lighthouse-client/assets/147052136/c78367d7-be1f-42f3-8e99-837203aa0ac7)

**Comment by MagnusGjosund** [comment]
I think it would be better to move the date to the banner. I feel like the banner is natural place to have the date. 

It will look like this
![Image](https://github.com/equinor/lighthouse-client/assets/54101675/e48365a7-aa69-463a-a178-b3215b2cf78b)

**Comment by MagnusGjosund** [comment]
PR: https://github.com/equinor/lighthouse-client/pull/1747

**Comment by EDUT-Equinor** [comment]
looks great :)

**Comment by EDUT-Equinor** [comment]
go fou push! awesome!
