### ISSUE TITLE
🐛 : Criteria Validation on non-existing criterieas

### ISSUE THREAD

**Issue by kjellhaaland** [equinor/lighthouse-client#1695]
The API throws lots of errors related to this issue.
Seems to be related to the app trying to do something with a criteria that does not exist.

 **The two error messages that are repeated are:**

- Sequence contains no elements.
- Criteria with id XXX(GUID) does not exist

**Example of a raw error message**
- [CriteriaDoesNotExistException.txt](https://github.com/equinor/lighthouse-client/files/14355957/CriteriaDoesNotExistException.txt)
- [SequenceContainsNoElements.txt](https://github.com/equinor/lighthouse-client/files/14355974/SequenceContainsNoElements.txt)

**Comment by BenSvend** [comment]
Status 26.02.2024:

Still getting Sequence contains no matching element error for ScopeChangeControl

**Comment by kjellhaaland** [comment]
Yes, i think this is fixed!
