### ISSUE TITLE
Add a Filter for "Contains Person"

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1696]
we want to allow users to search for what RCs they are involve in, useful for handovers between shifts. Please can we add a filter that pics up all the FRs / tasks assigned to individuals.

![image](https://github.com/equinor/lighthouse-client/assets/147052136/4edfe981-8258-4297-a8e0-fe37f95072fb)

**Comment by MagnusGjosund** [comment]
PR: https://github.com/equinor/lighthouse-client/pull/1714
