### ISSUE TITLE
Remove the status column, and null columns 

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1708]
comment out the status column, "Status" filter
resize the columns for system, switchboards, circuits, areas and commpks to roughtly what they are in the pic below. Then hide them as they are currently null fields
![image](https://github.com/equinor/lighthouse-client/assets/147052136/9ab8fd4a-be02-480f-8d98-fd5cebf8c2f4)

**Comment by MagnusGjosund** [comment]
PR: https://github.com/equinor/lighthouse-client/pull/1710
