### ISSUE TITLE
Change description of job creation

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1713]
After usage of the tool - a few changes to the description now we have loads of users... should make it easier to use

--- Required inputs ---
Requested by: 
Scaffolding [Yes/No]: 
--- Optional Inputs ---
SAP AO number (if applicable): 
PTW number(if applicable): 
Safety Critical HT involved (if applicable): 

Description of what is to be done (use the suggested wording below - if your not sure what to input for HT / other, just say not sure): 

(Example)
1.TAG:    HT:      Insu-Tag:      Job description:
2.TAG:    HT:      Insu-Tag:       Job description:

**Comment by MagnusGjosund** [comment]
PR: https://github.com/equinor/lighthouse-client/pull/1718
