### ISSUE TITLE
Remodel the Workflow tab to be more accessible & readable for the users

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1720]
Remodel the workflow. Include:

- some way to add checkboxes for tags - maybe with markdown?
- A button "Add all tags" to a workflow
- Allow free text next to a tag that has a checkbox
- Editable "descriptions" in the workflow 
- Add images in-line with workflow

Original Idea sheet -> superseded by Charlottes images in the comments section
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/69aadda0-1c51-4bf3-b20c-a0f16b6b8326)

**Comment by EDUT-Equinor** [comment]
Charlotte Janine Van den Berg "
I just made a couple of sketches to show some easy improvements for readability, that do not require so much programming, except for adding the tags with checkboxes to the step.
 
Showed description
Changed font sizes
Changed distances between steps
Text box width/column width can be a little wider. 
Move buttons with options for the step (three dots) to the front > Need to check whether this would be confusing when also the buttons for dragging to another step position are shown
Added button at the top to show already closed steps (which means that by default we could hide all steps that have been completed, but I would suggest to show at least one or two, so that the people working on the current step know what has been done lately.)

 Person who is not responsible for the step:
"
![Image](https://github.com/equinor/lighthouse-client/assets/147052136/f4bf95e9-8049-4a17-8dbb-95016e09151d)

![Image](https://github.com/equinor/lighthouse-client/assets/147052136/ee00ae2d-fb83-42ab-a39d-11eced99ac5a)

**Comment by LottevdBerg-OT** [comment]
https://www.figma.com/file/Lps3trwL5TErUCeNwoZvjM/Project-Portal?type=design&node-id=7894-46112&mode=dev
