### ISSUE TITLE
Optimize Custom_Scope_TagV1

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/lighthouse-client#1735]
We can optimize Custom_Scope_TagV1. 

Today the view is only used to get HeatTraces, and is only useed to search a HT and to get a HT. We could also remove a lot of fields in the view, since those is not used. The view is only used in RC.

![image](https://github.com/equinor/lighthouse-client/assets/54101675/59a05f46-1fb8-4590-864f-3e3427ce1609)

**Comment by EDUT-Equinor** [comment]
what is this issue? can we close?

**Comment by Gustav-Eikaas** [comment]
Aman says its closed
