### ISSUE TITLE
Filters for Priority 2 & Priority 3 in Punch analytics and Checklist

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1736]
Hei,

Management would like filters for priority 2 & 3 in Punch analytics and checklist. This is so we can see when checklist / punch needs to be completed after all the priority 1 dates finish in March / April, just before we go to the inshore phase and better assess punch priority.

There is big work going on at the moment to shift punches around to only be completed when they need to be completed. So we push punches from April 2024 -> Novemeber 2024 / even later, frees up time for more essential work to be done so its not so overwhelming for teams and they can prioritise more effectivly what is most urgent.

e.g., if we have a backlog of punches and have a **PB to put plastic caps on bolts** to stop them rusting, but we dont get round to doing the PB because there is so much other work "DUE" at the same time and the **PB to put plastic caps on the bolts** gets pushed to the back of the queue... then maybe the bolts rust, and we have to strip out the bolts and replace them because rust is infectious and will destroy the bolts making them weak.

![image](https://github.com/equinor/lighthouse-client/assets/147052136/23e85a6a-0c07-4caf-8fbd-28cc3499a742)
![image](https://github.com/equinor/lighthouse-client/assets/147052136/d5bc82ad-3af1-4e30-8159-8603801f7a9c)

Best,
Edward

**Comment by aman-riaz** [comment]
done: https://jc.fusion.equinor.com/ConstructionAndCommissioning/punch/analytics

(report is refreshing now, wil be ready for use in couple of minutes)

**Comment by ken-mellem** [comment]
@aman-riaz checklist as well?

**Comment by EDUT-Equinor** [comment]
Hei, could you add priority 2 & 3 to checklist too please :)

**Comment by aman-riaz** [comment]
Might have been to quick there. The filters are now availble for Checklists too :) 
https://jc.fusion.equinor.com/ConstructionAndCommissioning/checklist
