### ISSUE TITLE
PP Query analytics

### ISSUE THREAD

**Issue by JoneUE** [equinor/lighthouse-client#1745]
added some filters for commpkgs

new version here: 
https://statoilsrm.sharepoint.com/sites/FusioniPRD/Dashboards%20and%20MPP/Forms/AllItems.aspx?OR=Teams%2DHL&CT=1687341305262&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA1MDEwMDQyMiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&id=%2Fsites%2FFusioniPRD%2FDashboards%20and%20MPP%2FReports%20Into%20Fusion%20%28RIF%29%2FCCH%2FJohan%20Castberg%20Portal%2FProduction%2FPP%20Query&viewid=f853cde1%2D6ede%2D47a2%2Da60a%2D7a9b1e81dc92

**Comment by aman-riaz** [comment]
ready in prod: https://jc.fusion.equinor.com/Collaboration/query-workspace/analytics
