### ISSUE TITLE
Rename DisciplineReleaseControl -> piping & heat trace

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/lighthouse-client#1754]

**Comment by MagnusGjosund** [comment]
Changed all instances of DisciplineReleaseControl to PipingAndHeatTrace and disciplineReleaseControl to pipingAndHeatTrace in lighthouse-client. Everything builds and i've clicked around on localhost. Everything seems fine

**Comment by MagnusGjosund** [comment]
Couldn't find any instances of "DisciplineReleaseControl" in lighthouse-scope-change-contorl-api
