### ISSUE TITLE
🎁: Space out the "create a workflow" steps a little

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1772]
## Expected outcome

Space out the "create a workflow" steps a little - make it a little lovely for the users ;) 
![image](https://github.com/equinor/lighthouse-client/assets/147052136/c2969040-184c-45c2-842b-4f71e6482f1b)

**Comment by MagnusGjosund** [comment]
@Gustav-Eikaas done this. Please link your PR
