### ISSUE TITLE
🎁: Enhance the workflow design to be more aesthetically pleasing  

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1774]
## Expected outcome

the improvements we want for readability in the workflow.
1. REMOVED - hide previous steps
2. REMOVED - Two steps before current step are shown. 
3. NOTE: You can keep the description all on one line, as we currently have, we have shortened the workflow texts
4. text for functional roles should be smaller / can be a different font to break up the workflow
5. There is some space between each workflow step
6. enable the text from the sidesheet to be a bit wider, then there are fewer lines of text

![Image](https://github.com/equinor/lighthouse-client/assets/147052136/91f1946f-a873-49eb-b976-0558618ab0f0)

![image](https://github.com/equinor/lighthouse-client/assets/147052136/2a42393e-68a9-4fbf-812c-54f45427bc81)

**Comment by EDUT-Equinor** [comment]
looks good :) - go for push - i think you stull cant drag the workflow steps, but i guess thats being handled somewhere else?

**Comment by MagnusGjosund** [comment]
PR: https://github.com/equinor/lighthouse-client/pull/1788
