### ISSUE TITLE
🐛: switchboard/circuit appears multiple times

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1777]
## Description

Makes the circuits and switchboards appear just once please :) 

![image](https://github.com/equinor/lighthouse-client/assets/147052136/1bca6bc6-c4db-48c3-9dd3-2484f9793b55)

**Comment by ken-mellem** [comment]
@MagnusGjosund for now - can we simply do a unique in FrontEnd?

**Comment by MagnusGjosund** [comment]
PR: https://github.com/equinor/lighthouse-client/pull/1797

**Comment by ken-mellem** [comment]
Taking this out of Must Have as we have a front-end fix. Closing for now.
