### ISSUE TITLE
🐛: Pipetest: Status is wrong compared to checklists

### ISSUE THREAD

**Issue by JoneUE** [equinor/lighthouse-client#1791]
## Description

![Image](https://github.com/equinor/lighthouse-client/assets/73601851/b2a292bf-0253-4b44-b7a3-cf4de6e65178)

**Comment by atlewee** [comment]
ZB regnes ikke fra disse sjekklistene (ZB er noe vi har laget, finnes ikke i ProCoSys)
Bruker MCCR's på box tag knyttet til pipetest, ikke disse vanlige dummytaggene
Så ser riktig ut det som vises i dette bildet
