### ISSUE TITLE
🎁: RC - Bug and wrong data in PBI report 

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/lighthouse-client#1803]
## Expected outcome

Seems like the report is showing wrong data/outdated data. As it is now, it is useless :(  

Change the data fundation in the diagram in the PBI report in RC. The user needs to see createdAt in the diagram. E.g. so they can see how many RCs that is beeing made every week. 

![image](https://github.com/equinor/lighthouse-client/assets/54101675/981dc68b-a636-4d45-a659-12d46667d233)

## Business Value / Developer Experience

Wants to have a reliable report that shows the correct data and the users wants to track how many RCs beeing made over a time period

## Acceptance Criteria

Needs to have the correct data, and needs to be able to see how many RCs that are beeing made over a time period

**Comment by JoneUE** [comment]
The analytics have been fixed
