### ISSUE TITLE
🎁: CC Overview  - complete rework of report

### ISSUE THREAD

**Issue by JoneUE** [equinor/lighthouse-client#1813]
## Expected outcome

The report that was Completion analytics will now replace Overview report in JC portal. I made a new version, and then just overwrite the old PP CCH overview report

https://statoilsrm.sharepoint.com/sites/FusioniPRD/Dashboards%20and%20MPP/Forms/AllItems.aspx?OR=Teams%2DHL&CT=1687341305262&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA1MDEwMDQyMiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&id=%2Fsites%2FFusioniPRD%2FDashboards%20and%20MPP%2FReports%20Into%20Fusion%20%28RIF%29%2FCCH%2FJohan%20Castberg%20Portal%2FProduction%2FPP%20CCH%20Overview&viewid=f853cde1%2D6ede%2D47a2%2Da60a%2D7a9b1e81dc92

**Comment by aman-riaz** [comment]
As agreed with Jone the new version of CCH PP Overview has now been published to production, and can be found here: https://jc.fusion.equinor.com/ConstructionAndCommissioning/cch-overview

@JoneUE
