### ISSUE TITLE
🐛: CC-Overview report does not update data

### ISSUE THREAD

**Issue by atlewee** [equinor/lighthouse-client#1819]
## Description

The following report:
https://jc.fusion.equinor.com/ConstructionAndCommissioning/cch-overview
Has outdated data, the numbers is not correct.

## Reproduce
Open https://jc.fusion.equinor.com/ConstructionAndCommissioning/cch-overview
See that last update is a few weeks old.
![image](https://github.com/equinor/lighthouse-client/assets/11732817/0067eebf-cced-4de2-a093-31e04b11db50)

## Expected behavior

Updated data.. (Outstanding RFO shoud be around 116, not 156)

**Comment by aman-riaz** [comment]
This is now resolved.

Refresh had failed due to missing credentials for a new data source that has been added (sharepoint list)
