### ISSUE TITLE
🐛: Handover application does not load

### ISSUE THREAD

**Issue by atlewee** [equinor/lighthouse-client#1844]
## Description

User reports that Handover application stopped working a couple of days ago
It says "Loading Application" forever

## Reproduce

I testet it now and get the same issue:
![image](https://github.com/equinor/lighthouse-client/assets/11732817/f10611e2-2863-4590-b0c1-4e78358e5518)

## Expected behavior

Handovcer application loads

**Comment by Gustav-Eikaas** [comment]
Fixed by #1856
