### ISSUE TITLE
JC-Portal: migrate to fusion app management v2 api

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/lighthouse-client#1858]
Following the release of app management v2 api we need to migrate to the new api 

This comes with some challenges, namely chunking; Fusions endpoint for fetching .js resources require a jwt token. Upon bootstrapping a bundle the javascript code will automatically try to fetch required modules when the code that needs it is invoked. This makes it impossible to attach a jwt token. The only real way to solve this is to setup a reverse proxy with cookie auth that can transform the cookie into a jwt token.

Migration guide supplied by fusion 
- equinor/fusion-rfcs#70

**Comment by ken-mellem** [comment]
We need to make a decision regarding JC Portal.
