### ISSUE TITLE
🐛: SCR error message

### ISSUE THREAD

**Issue by JoneUE** [equinor/lighthouse-client#1859]
## Description

Det er en error message når de prøver å lager en revision på SCR

![Image](https://github.com/user-attachments/assets/412dffb1-f9cb-4298-95cc-8e59de27c844)

**Comment by ken-mellem** [comment]
@Jossilainen is this still relevant?

**Comment by Jossilainen** [comment]
I have not looked into this one. But I can see that the relevant request is now revised to SCR-2131-02 and gone through the workflow. Probably not relevant
